### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by nekopa** [gusthoff/kanboard-plugin-column-group#1] opened 2016-10-30 10:25 UTC
Hi there, 
When I try to copy from the archive to /plugins, it take down my whole Kanboard leaving me with this message:

Internal Error: Unable to migrate schema for the plugin: ColumnGroup => SQLSTATE[HY000]: General error: 1 near "FOREIGN": syntax error

It is a fresh install of Kanboard, using the kanboard-1.0.34.zip archive. I'm using sqlite.

**Comment by gusthoff** [comment] 2016-11-01 11:48
Thanks for reporting! The issue should be fixed now.

**Comment by nekopa** [comment] 2016-11-01 17:54
Thanks for responding! It installs ok now. 

But (and I don't know if this is the place to mention this) I can't seem to do anything with it.

If I go into the column group area of the board, and try to edit a column, it pops up a modal where nothing is selectable or changeable for me.

How do I, for example, split the Backlog column into Backlog-new and Backlog-prepped column group?

Oh, I am running:
Xubuntu 15.10
PHP 5.6.11-1ubuntu3.4 
Apache2

Please let me know if you need anymore info. I really want to get this to work :)

**Comment by Busfreak** [comment] 2016-11-01 18:43
You can create column groups as admin, in the global settings. Not for a board.
See https://github.com/gusthoff/kanboard-plugin-column-group/issues/4

**Comment by gusthoff** [comment] 2016-11-03 20:55
This plug-in does not support splitting columns. As @Busfreak was saying, in order to create column groups, you need to go to the global settings. For example, if Kanboard is installed on your local machine:

http://127.0.0.1/kanboard/?controller=ConfigColumnGroupController&action=index&plugin=ColumnGroup

In order to use the column groups you've just created in a project, you need to go to the project settings. For example:

http://127.0.0.1/kanboard/?controller=ProjectColumnGroupController&action=index&plugin=ColumnGroup&project_id=1

Since the issue is actually fixed, I'll be closing this thread.

**Closed as completed by gusthoff** 2016-11-03 20:55 UTC
Labels: bug
